from tkinter import *
from tkinter import messagebox
import sqlite3   
def welcome():
    w=Tk()
    w.title("Railway Ticket Booking")
    w.geometry('1366x768')
    w.config(bg='Light Pink')
    def logout():
        w.destroy()
        login()
    lbl2=Label(w,text="Logged in Successfully.....",font=("Bell MT",15),bg='Light Pink')
    lbl3=Label(w,text="Welcome User",font=("Bell MT",18),bg='Light Pink')
    btn=Button(w,text="Log out",font=("Bell MT",10),width=5,command=logout).place(x=10,y=90)
    lbl2.place(x=10,y=20)
    lbl3.place(x=10,y=50)
    w.mainloop()

'''def fail():
    w=Tk()
    w.withdraw()
    messagebox.showerror("Error","Incorrect Username and Password")
    login()
    w.mainloop()'''

def register():
    w = Tk ()
    w.title("Railway Ticket Booking")
    w.geometry('1366x768')
    w.config(bg='Light Pink')
    Fn=StringVar()
    Ln=StringVar()
    Un=StringVar()
    Pw=StringVar()
    lbl5=Label(w,text="Sign in",font=("Bell MT",25),bg='Light Pink')
    lbl5.place(x=560,y=145)
    lbl1=Label(w,text="First name:",font=("Bell MT",15),bg='Light Pink')
    lbl1.place(x=470,y=220)
    lbl2=Label(w,text="Last name:",font=("Bell MT",15),bg='Light Pink')
    lbl2.place(x=470,y=270)
    lbl3=Label(w,text="User name :",font=("Bell MT",15),bg='Light Pink')
    lbl3.place(x=470,y=320)
    lbl4=Label(w,text="Password :",font=("Bell MT",15),bg='Light Pink')
    lbl4.place(x=470,y=370)
    FIRSTNAME=Entry(w,width=30)
    FIRSTNAME.place(x=590,y=225)
    LASTNAME=Entry(w,width=30)
    LASTNAME.place(x=590,y=275)
    USERNAME=Entry(w,width=30)
    USERNAME.place(x=590,y=325)
    PASSWORD=Entry(w,width=30,show="*")
    PASSWORD.place(x=590,y=375)
    def home():
        w.destroy()
        login()
    btn=Button(w,text="Submit",font=("Bell MT",8),width=15,command=login).place(x=630,y=420)
    btn1=Button(w,text="Back to home",font=("Bell MT",7),width=15,command=home).place(x=590,y=450)
            
def login():
    w = Tk ()
    w.title("Quizpy")
    w.geometry('1366x768')
    w.config(bg='Light blue')
    lbl3=Label(w,text="Railway Ticket Booking",font=("Bell MT",50),bg='blue')
    #lbl3.place(x=370,y=50)
    lbl3.pack(side=TOP,fill=X)
    lbl4=Label(w,text="Seat Reservation System",font=("Bell MT",20),bg='Light blue')
    lbl4.place(x=490,y=100)
    lbl5=Label(w,text="***Please, log in if you have already registered***",font=("Bell MT",20),bg='Light blue')
    lbl5.place(x=400,y=150)
    lbl1=Label(w,text="User name :",font=("Bell MT",15),bg='Light blue')
    lbl1.place(x=470,y=190)
    lbl2=Label(w,text="Password :",font=("Bell MT",15),bg='Light blue')
    lbl2.place(x=470,y=270)
    lbl2=Label(w,text="New user?",font=("Bell MT",12),bg='Light blue')
    lbl2.place(x=590,y=360)
    ent1=Entry(w,width=30,borderwidth=3,relief=SUNKEN)
    ent1.place(x=590,y=190)
    ent2=Entry(w,width=30,show="*")
    ent2.place(x=590,y=275)
    def clicked():
        if ent1.get()=="Suraj" and ent2.get()=='1905':
            w.destroy()
            welcome()
        else:
            messagebox.showerror("Error","Incorrect Username and Password")
    btn=Button(w,text="Log in",font=("Bell MT",10),width=15,command=clicked).place(x=590,y=320)
    btn1=Button(w,text="Register",font=("Bell MT",10),width=7,command=register).place(x=670,y=360)
    #photo=PhotoImage(file='C:/Users/suraj/Desktop/Project/Quiz.png')
    #label=Label(w,image=photo)
    #label.place(x=0,y=0,relwidth=1,relheight=1)
    w.mainloop()
login()
